### ISSUE TITLE
module load unsets SINGULARITY_OPTS=--nv

### ISSUE THREAD

**Issue by surak** [singularityhub/singularity-hpc#480] opened 2022-02-03 18:51 UTC
Hi, I just started using this software and I already love it.

One thing I realized it that this mention of gpus in https://singularity-hpc.readthedocs.io/en/latest/getting_started/use-cases.html?highlight=gpu#adding-options says:

```
By default, some of the commands will come with singularity options. For example, a container intended for gpu is always going to give you the --nv flag. However, it could be the case that you want to define custom options at the time of use. In this case, you can export the following custom environment variables to add them
```

I tried a grand total of two gpu containers from the ones on the default list: 
`nvcr.io/nvidia/pytorch/21.11-py3/module` and `tensorflow/tensorflow/2.7.0/module`

Neither of them comes with the `--nv` option set. In fact, it unsets it:

```bash
$ export SINGULARITY_OPTS="--nv"
$ echo $SINGULARITY_OPTS 
--nv
$ ml tensorflow/tensorflow
$ echo $SINGULARITY_OPTS 

$
```

Plus, there is no mention of `--nv` on the module spider of the aforementioned containers:

```bash

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  tensorflow/tensorflow: tensorflow/tensorflow/2.7.0/module
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    Description:
      An end-to-end open source platform for machine learning.


    This module can be loaded directly: module load tensorflow/tensorflow/2.7.0/module

    Help:
      This module is a singularity container wrapper for tensorflow/tensorflow v2.7.0
      An end-to-end open source platform for machine learning.
      
      Container:
      
       - /home/strube1/singularity-hpc/modules/tensorflow/tensorflow/2.7.0/tensorflow-tensorflow-2.7.0-sha256:31e09cf438a41f12c759cc8cc79c6b0fbb0db5abfc3de8169e916c8c9ac38dc5.sif
      
      Commands include:
      
       - tensorflow-run:
             singularity run -B /home/strube1/singularity-hpc/modules/tensorflow/tensorflow/2.7.0/99-shpc.sh:/.singularity.d/env/99-shpc.sh <container>
       - tensorflow-shell:
             singularity shell -s /bin/sh -B /home/strube1/singularity-hpc/modules/tensorflow/tensorflow/2.7.0/99-shpc.sh:/.singularity.d/env/99-shpc.sh <container>
       - tensorflow-exec:
             singularity exec -B /home/strube1/singularity-hpc/modules/tensorflow/tensorflow/2.7.0/99-shpc.sh:/.singularity.d/env/99-shpc.sh <container> "$@"
       - tensorflow-inspect-runscript:
             singularity inspect -r <container>
       - tensorflow-inspect-deffile:
             singularity inspect -d <container>
      
       - python:
             singularity exec -B /home/strube1/singularity-hpc/modules/tensorflow/tensorflow/2.7.0/99-shpc.sh:/.singularity.d/env/99-shpc.sh <container> /usr/local/bin/python
      
      
      For each of the above, you can export:
      
       - SINGULARITY_OPTS: to define custom options for singularity (e.g., --debug)
       - SINGULARITY_COMMAND_OPTS: to define custom options for the command (e.g., -b)
```

And worse:

setting it again breaks things:

```
$ ml tensorflow/tensorflow
$ export SINGULARITY_OPTS="--nv"
$ python
python
Error: unknown command "/home/strube1/singularity-hpc/modules/tensorflow/tensorflow/2.7.0/tensorflow-tensorflow-2.7.0-sha256:31e09cf438a41f12c759cc8cc79c6b0fbb0db5abfc3de8169e916c8c9ac38dc5.sif" for "singularity"

Error for command "singularity": unknown flag: --nv
```

Am I missing something here? 

Thanks!

**Comment by vsoch** [comment] 2022-02-03 19:03
Oh interesting - so it looks like the envar is being carried forward (because you do ask for the `--nv` flag) but perhaps that Singularity installed on your cluster doesn't support it? Could you look at the module file directly and show me the alias for Python, and then test it 1. without the flag (won't support GPU) and then 2. with the flag to reproduce the error above?

I'm interested to know what version (provider sylabs or apptainer) and version number of singularity you are using too.

**Comment by vsoch** [comment] 2022-02-03 19:04
And since the envar is in the environment for the user, we don't show it in the module file.

**Comment by surak** [comment] 2022-02-03 19:06
Hi!

This is the version of singularity I have
```singularity version 3.8.4-1.el8```

And it seems that the module does unset it on purpose. I don't know how is the template for module generation used:

```lua
cat module.lua 
-- Lmod Module
-- Created by singularity-hpc (https://github.com/singularityhub/singularity-hpc)
-- ##
-- tensorflow/tensorflow on 2022-02-03 18:02:27.168657
--

help(
[[
This module is a singularity container wrapper for tensorflow/tensorflow v2.7.0
An end-to-end open source platform for machine learning.

Container:

 - /home/strube1/singularity-hpc/modules/tensorflow/tensorflow/2.7.0/tensorflow-tensorflow-2.7.0-sha256:31e09cf438a41f12c759cc8cc79c6b0fbb0db5abfc3de8169e916c8c9ac38dc5.sif

Commands include:

 - tensorflow-run:
       singularity run -B /home/strube1/singularity-hpc/modules/tensorflow/tensorflow/2.7.0/99-shpc.sh:/.singularity.d/env/99-shpc.sh <container>
 - tensorflow-shell:
       singularity shell -s /bin/sh -B /home/strube1/singularity-hpc/modules/tensorflow/tensorflow/2.7.0/99-shpc.sh:/.singularity.d/env/99-shpc.sh <container>
 - tensorflow-exec:
       singularity exec -B /home/strube1/singularity-hpc/modules/tensorflow/tensorflow/2.7.0/99-shpc.sh:/.singularity.d/env/99-shpc.sh <container> "$@"
 - tensorflow-inspect-runscript:
       singularity inspect -r <container>
 - tensorflow-inspect-deffile:
       singularity inspect -d <container>

 - python:
       singularity exec -B /home/strube1/singularity-hpc/modules/tensorflow/tensorflow/2.7.0/99-shpc.sh:/.singularity.d/env/99-shpc.sh <container> /usr/local/bin/python


For each of the above, you can export:

 - SINGULARITY_OPTS: to define custom options for singularity (e.g., --debug)
 - SINGULARITY_COMMAND_OPTS: to define custom options for the command (e.g., -b)
]]) 



-- we probably don't need this
local MODULEPATH="/home/strube1/singularity-hpc/modules/tensorflow/tensorflow/2.7.0"

-- singularity environment variables to bind the paths and set shell

setenv("SINGULARITY_SHELL", "/bin/sh")
setenv ("SINGULARITY_OPTS", "")
setenv ("SINGULARITY_COMMAND_OPTS", "")

-- interactive shell to any container, plus exec for aliases
local containerPath = '/home/strube1/singularity-hpc/modules/tensorflow/tensorflow/2.7.0/tensorflow-tensorflow-2.7.0-sha256:31e09cf438a41f12c759cc8cc79c6b0fbb0db5abfc3de8169e916c8c9ac38dc5.sif'
local shellCmd = "singularity ${SINGULARITY_OPTS} shell ${SINGULARITY_COMMAND_OPTS} -s /bin/sh -B /home/strube1/singularity-hpc/modules/tensorflow/tensorflow/2.7.0/99-shpc.sh:/.singularity.d/env/99-shpc.sh  " .. containerPath
local execCmd = "singularity ${SINGULARITY_OPTS} exec ${SINGULARITY_COMMAND_OPTS} -B /home/strube1/singularity-hpc/modules/tensorflow/tensorflow/2.7.0/99-shpc.sh:/.singularity.d/env/99-shpc.sh  "
local runCmd = "singularity ${SINGULARITY_OPTS} run ${SINGULARITY_COMMAND_OPTS} -B /home/strube1/singularity-hpc/modules/tensorflow/tensorflow/2.7.0/99-shpc.sh:/.singularity.d/env/99-shpc.sh  " .. containerPath
local inspectCmd = "singularity ${SINGULARITY_OPTS} inspect ${SINGULARITY_COMMAND_OPTS} " 

-- set_shell_function takes bashStr and cshStr
set_shell_function("tensorflow-shell", shellCmd,  shellCmd)

-- conflict with modules with the same name
conflict(myModuleName(),"python")

-- exec functions to provide "alias" to module commands

set_shell_function("python", execCmd ..  containerPath .. " /usr/local/bin/python $@", execCmd ..  containerPath .. " /usr/local/bin/python")



if (myShellName() == "bash") then
execute{cmd="export -f python", modeA={"load"}}

end

-- A customizable exec function
set_shell_function("tensorflow-exec", execCmd .. containerPath .. " $@",  execCmd .. containerPath)

-- Always provide a container run
set_shell_function("tensorflow-run", runCmd .. " $@",  runCmd)

-- Inspect runscript or deffile easily!
set_shell_function("tensorflow-inspect-runscript", inspectCmd .. " -r  " .. containerPath,  inspectCmd .. containerPath)
set_shell_function("tensorflow-inspect-deffile", inspectCmd .. " -d  " .. containerPath,  inspectCmd .. containerPath)

whatis("Name        : " .. myModuleName())
whatis("Version     : " .. myModuleVersion())
whatis("Description    : An end-to-end open source platform for machine learning.")
whatis("Url         : https://hub.docker.com/r/tensorflow/tensorflow")
whatis("org.label-schema.build-arch    : amd64")
whatis("org.label-schema.build-date    : Thursday_3_February_2022_18:2:12_UTC")
whatis("org.label-schema.schema-version    : 1.0")
whatis("org.label-schema.usage.singularity.deffile.bootstrap    : docker")
whatis("org.label-schema.usage.singularity.deffile.from    : tensorflow/tensorflow@sha256:31e09cf438a41f12c759cc8cc79c6b0fbb0db5abfc3de8169e916c8c9ac38dc5")
whatis("org.label-schema.usage.singularity.version    : 3.8.4-1.el8")
```

**Comment by vsoch** [comment] 2022-02-03 19:08
@surak if ahh I see - so there are two issues here!

1. you are saying that if you set the envar _before_ module loading, it is unset, and we shouldn't unset it (but if you set it after loading it does still work, per your example)
2. Singularity doesn't seem to honor the --nv flag

Could you look at the singularity exec command and see if there is some mention of gpu or a flag?

**Comment by surak** [comment] 2022-02-03 19:14
So, yes, I am finding issues :-)

- One is that the variable is unset. That should not be the case.
- Another one is that the command "python" does not honor the flag, although `execCmd`, `runCmd` and `inspectCmd` do honor the flag.
- A third issue is that the `tensorflow/tensorflow` container is compiled without gpu support (should I open a new one on this?)

**Comment by vsoch** [comment] 2022-02-03 19:17
> Another one is that the command "python" does not honor the flag, although execCmd, runCmd and inspectCmd do honor the flag.

I'm not understanding this - from your output it does appear that python is asking for `--nv` and the singularity software is saying "I don't support this" - this is why I was asking if you could test the exec to the container with the flag outside of the context of shpc.

> One is that the variable is unset. That should not be the case.

Totally agree!  And indeed it looks like the execCommand includes the envars -

```
local execCmd = "singularity ${SINGULARITY_OPTS} exec ${SINGULARITY_COMMAND_OPTS} -B /home/strube1/singularity-hpc/modules/tensorflow/tensorflow/2.7.0/99-shpc.sh:/.singularity.d/env/99-shpc.sh  "
```
but we unset them!

```
setenv("SINGULARITY_SHELL", "/bin/sh")
setenv ("SINGULARITY_OPTS", "")
setenv ("SINGULARITY_COMMAND_OPTS", "")
```
I think what it's doing is setting them at the time of module generation, which we don't want - we want to just grab them from the user. Ping @marcodelapierre if you know how to do this - I'll be able to take a look later tonight!

> A third issue is that the tensorflow/tensorflow container is compiled without gpu support (should I open a new one on this?)

Based on the recipe, I think you would need to ask for a tag that includes gpu? The default afaik does not. https://github.com/singularityhub/singularity-hpc/blob/bfb2c33796d60e291639e0725f00b3bcff084aa7/registry/tensorflow/tensorflow/container.yaml#L8. If there is a tag there missing (that you see on Docker Hub that you want to include) we can definitely add it.

**Comment by surak** [comment] 2022-02-03 19:21
I don't know how to ask for it. shpc gives me this:

```bash
shpc install tensorflow/tensorflow:latest-gpu
tensorflow/tensorflow:gpu is not a known identifier. Choices are:
2.2.2
2.5.0-custom-op-gpu-ubuntu16
2.5.0rc0-gpu-jupyter
2.6.0
2.6.0rc0-gpu-jupyter
2.7.0
2.7.0rc0
```

**Comment by vsoch** [comment] 2022-02-03 19:22
Ah! So we need to add latest-gpu (which isn't in that set!) if you want to do a quick PR to the file that I mentioned (you'll need to grab the sha from the Docker Hub page) we can fix that asap, otherwise I can do it tonight.

**Comment by vsoch** [comment] 2022-02-03 19:43
@surak if you remove those two lines in the module file :+1: 
```
setenv ("SINGULARITY_OPTS", "")
setenv ("SINGULARITY_COMMAND_OPTS", "")
```
does that fix it? E.g., does the envar you set before load still exist in the environment and is grabbed by the container?

**Comment by surak** [comment] 2022-02-03 20:06
Okay, I figured that the `--nv` has to be on the `SINGULARITY_COMMAND_OPTS`, since this is a flag for the `exec` command. Which means that the documentation should mention this. I will fix it there: #482

**Comment by surak** [comment] 2022-02-03 20:21
#481 was wrong on tcsh (which I haven't used since the 80s, sorry)

#483 should do the trick

**Comment by vsoch** [comment] 2022-02-04 02:26
@marcodelapierre I just merged a PR to add gpu true to PyTorch - let me know if there are others!

**Comment by vsoch** [comment] 2022-02-04 13:18
Fixed with https://github.com/singularityhub/singularity-hpc/pull/483. @surak please ping again if there are further issues.

**Closed by vsoch** 2022-02-04 13:18 UTC
