### ISSUE TITLE
Container pulled to cwd not container_base

### ISSUE THREAD

**Issue by audreystott** [singularityhub/singularity-hpc#522] opened 2022-03-22 02:50 UTC
When running `shpc install`, the container is pulled successfully but to the current working directory instead of the container_base location. There is also an error message - "There was an issue pulling None" after the container has been pulled.

`shpc install quay.io/biocontainers/trimmomatic
singularity pull --name quay.io-biocontainers-trimmomatic-0.39--hdfd78af_2-sha256:b52e7e3159fda36b7b5c119a9a1e673e6a63e480eff8617b689c031f76998870.sif [docker://quay.io/biocontainers/trimmomatic@sha256:b52e7e3159fda36b7b5c119a9a1e673e6a63e480eff8617b689c031f76998870]()
INFO:    Using cached SIF image
There was an issue pulling None`

This only happened with v 0.0.48, but was not reproduced in 0.0.45

I have mentioned it to @marcodelapierre who advised me to try it with 0.0.45.

**Comment by vsoch** [comment] 2022-03-22 03:54
That's strange - I see markdown in your pull, as if there is an underlying but. What version of singularity are you using? As an example, here is what pull looks like for me with the same container:

```
singularity pull --name /home/vanessa/Desktop/Code/shpc/containers/quay.io/biocontainers/trimmomatic/0.39--hdfd78af_2/quay.io-biocontainers-trimmomatic-0.39--hdfd78af_2-sha256:b52e7e3159fda36b7b5c119a9a1e673e6a63e480eff8617b689c031f76998870.sif docker://quay.io/biocontainers/trimmomatic@sha256:b52e7e3159fda36b7b5c119a9a1e673e6a63e480eff8617b689c031f76998870
```
I'm thinking there is a difference with respect to either:

1. the singularity version (I typically test wit 3.8.x and up)
2. the singularity python, spython version (make sure you have the latest)

I'm concerned about that markdown in the pull command for (what should be) just the path to the image. Could you look into the above and report back? And see the extent that you can debug by following the shpc source code? I'll be able to better help if we can track down the bug (since I can't reproduce it).

**Comment by audreystott** [comment] 2022-03-23 02:05
Thanks Vanessa. I have to clarify, I installed Apptainer v1.0.0, instead of the old Singularity. And the markdown was actually from copying and pasting from Slack instead of my terminal. So please ignore it. On the terminal it doesn't have the markdown. I will have to get back to you on the debug stuff.

**Comment by vsoch** [comment] 2022-03-23 02:36
Sounds good!

And if it makes a difference (I am not following apptainer development) I will generally be following Sylabs Singularity for all the tools I maintain. They are hopefully close enough now (and will continue to be) that it won’t make a difference, but it’s hard to tell.

**Comment by vsoch** [comment] 2022-03-23 02:38
And also to clarify, Sylabs Singularity is not an “old” Singularity, in fact many Apptainer commits come from there. It reflects drama in the community that was not resolved that (hopefully) we can put behind us.

**Comment by marcodelapierre** [comment] 2022-03-23 04:54
I can confirm it works for me with:
* singularity 3.8.5 
* python 3.9.7
* spython 0.1.18

**Comment by marcodelapierre** [comment] 2022-03-23 05:05
Audrey says
* shpc 0.0.48 (error) , 0.0.45 (works)
* apptainer 1.0.0
* python 3.6.8
* spython 0.1.18

Python 3.6.x should be fine I reckon...?
If it works for 45 but not 48, I suspect it might be the changes that entered in 46, aimed at fixing the repeated pull output...?
But then the trigger still seems to be Apptainer vs Singularity

**Comment by vsoch** [comment] 2022-03-23 05:27
perhaps try the native pull (the command I showed, or a derivative of it) with apptainer natively? Oh vey I hope their aren't UI differences already, I could never keep up supporting two different Singularity's. :sob:

**Comment by audreystott** [comment] 2022-03-23 08:10
I tried the native pull and got no errors. Looks like we will keep testing with SingularityCE for now.

**Comment by vsoch** [comment] 2022-03-27 05:32
Sounds good! Let me know if you want to chat about anything else, or if we are good to close this issue. Also ping @georgiastuart in case you are using Apptainer too - it looks like from this issue there are already discrepancies (and here I will be developing to support SingularityCE primarily).

**Comment by georgiastuart** [comment] 2022-03-27 10:52
@vsoch we're on Singularity 3.8.6. My center has not decided which path to go down yet, but it's good to know your tools will be following SingularityCE. However, I have a local install of Apptainer that I can poke around on with shpc to see if there's a quick fix that would enable compatibility with both "forks." Can you leave the issue open for a couple days?

**Comment by georgiastuart** [comment] 2022-03-27 15:55
The fix was just adding a check for Apptainer in the `pull` function in `spython` and did not modify functionality anywhere else. It appears Apptainer and SingularityCE haven't diverged on the CLI at all and Apptainer still honors singularity env variables, etc, so it was just a matter of including Apptainer in the check for Singularity 3+.

However, if you don't want to support Apptainer, I understand if y'all reject the PR!

**Comment by vsoch** [comment] 2022-03-27 17:58
Hmm, perhaps it would make sense to allow an environment variable for the user to change the executable name to whatever they like? That seems harmless enough!

**Comment by georgiastuart** [comment] 2022-03-27 19:06
I can confirm this is fixed with Apptainer 1.0.1 with https://github.com/singularityhub/singularity-cli/pull/191!

**Comment by vsoch** [comment] 2022-03-27 19:08
holy cow you tested it 38 seconds before I commented? I think you must be a superhero @georgiastuart. Will have this merged and released right away!

**Comment by vsoch** [comment] 2022-03-27 19:21
What we can do is now to require that version as spython as a minimum - will put in a PR for that shortly. @audreystott you should then be able to install shpc and get that version!

**Comment by vsoch** [comment] 2022-03-27 19:43
@audreystott based on @georgiastuart testing, this should be fixed if you either install the latest spython, or use release https://github.com/singularityhub/singularity-hpc/releases/tag/0.0.51 of singularity-hpc that will require it.

Closing issue - please re-open or comment if you find another issue!

**Closed by vsoch** 2022-03-27 19:43 UTC
